export  const  FETCH_LEVIES_REQUEST="FETCH_LEVIES_REQUEST";
export  const  FETCH_LEVIES_SUCCESS="FETCH_LEVIES_SUCCESS";
export  const  FETCH_LEVIES_FAILURE="FETCH_LEVIES_FAILURE";


export  const  FETCH_EXTENSIONS_REQUEST="FETCH_EXTENSIONS_REQUEST";
export  const  FETCH_EXTENSIONS_SUCCESS="FETCH_EXTENSIONS_SUCCESS";
export  const  FETCH_EXTENSIONS_FAILURE="FETCH_EXTENSIONS_FAILURE";


export  const  FETCH_BENEFITS_REQUEST="FETCH_BENEFITS_REQUEST";
export  const  FETCH_BENEFITS_SUCCESS="FETCH_BENEFITS_SUCCESS";
export  const  FETCH_BENEFITS_FAILURE="FETCH_BENEFITS_FAILURE";

export  const  FETCH_TRANSACTIONS_REQUEST="FETCH_TRANSACTIONS_REQUEST";
export  const  FETCH_TRANSACTIONS_SUCCESS="FETCH_TRANSACTIONS_SUCCESS";
export  const  FETCH_TRANSACTIONS_FAILURE="FETCH_TRANSACTIONS_FAILURE";

export  const  FETCH_CUSTOMER_DETAILS_REQUEST="FETCH_CUSTOMER_DETAILS_REQUEST";
export  const  FETCH_CUSTOMER_DETAILS_SUCCESS="FETCH_CUSTOMER_DETAILS_SUCCESS";
export  const  FETCH_CUSTOMER_DETAILS_FAILURE="FETCH_CUSTOMER_DETAILS_FAILURE";

export  const  FETCH_LOADING_REQUEST="FETCH_LOADING_REQUEST";
export  const  FETCH_LOADING_SUCCESS="FETCH_LOADING_SUCCESS";
export  const  FETCH_LOADING_FAILURE="FETCH_LOADING_FAILURE";

